version: "3.8"

services:
  peer1:
    build: ./
    environment:
      LOCAL_NODE: 192.168.0.142
      ID: "m1"
    networks:
      vpcbr:
        ipv4_address: 192.168.0.142
    tty: true

  peer2:
    build: ./
    environment:
      LOCAL_NODE: 192.168.0.143
      ID: "m2"
    networks:
      vpcbr:
        ipv4_address: 192.168.0.143
    tty: true
  peer3:
    build: ./
    environment:
      LOCAL_NODE: 192.168.0.144
      ID: "m3"
    networks:
      vpcbr:
        ipv4_address: 192.168.0.144
    tty: true
  peer4:
    build: ./
    environment:
      LOCAL_NODE: 192.168.0.145
      ID: "m4"
    networks:
      vpcbr:
        ipv4_address: 192.168.0.145
    tty: true
  peer5:
    build: ./
    environment:
      LOCAL_NODE: 192.168.0.146
      ID: "m5"
    networks:
      vpcbr:
        ipv4_address: 192.168.0.146
    tty: true
  peer6:
    build: ./
    environment:
      LOCAL_NODE: 192.168.0.147
      ID: "m6"
    networks:
      vpcbr:
        ipv4_address: 192.168.0.147
    tty: true
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
